language: node_js
node_js:
    - 14
# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
    apt:
        packages:
            - libgconf-2-4
cache: yarn
install:
    - yarn install --frozen-lockfile
    - yarn build
    - yarn lint
    - yarn test
    - yarn admin cy:verify
    - yarn start
script:
    - yarn wait-on http-get://0.0.0.0:8000
    - yarn cy:run
