language: node_js
node_js:
    - 14
# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
    apt:
        packages:
            - libgconf-2-4
cache:
    yarn: true
    directories:
        - $HOME/.cache
          # install dependencies and check that Cypress can run
    override:
        - yarn install --frozen-lockfile
        - yarn admin cy:verify
script:
    - yarn build
    - yarn lint
    - yarn test
    - yarn start &
    - yarn wait-on http-get://0.0.0.0:8000
    - yarn admin cy:run
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true
