language: node_js
node_js:
    - 14
# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
    apt:
        packages:
            - libgconf-2-4
cache: yarn
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
    - export PATH="$HOME/.yarn/bin:$PATH"
install:
    - yarn install --frozen-lockfile
    - yarn build
    - yarn admin cy:verify
    - yarn start
script:
    - yarn wait-on http-get://localhost:8000
    - yarn cy:e2e:run
